Basic support for themeing plots
creativescala/chartreuse pull request #23
Opened 2023-08-08 14:20 UTC by noelwelsh

This WIP adds basic support for theming plots. What we have:

* A way to represent style values that can be overridden by a theme, or override a theme
* A way to represent a theme
* Very basic implementation for `Layout`

Things to do:

- [x] Implement some actual themes
- [x] Pass themes through from `Plot`
- [x] Complete documentation
- [x] Correct typos: themeing -> theming

To consider:

- Should there be a hierarchy of themes, and inheritance between them.
- Clean up `Glyph` implementation, so it doesn't have its own theming code
- Add colour back to our examples. I.e. add a default theme that looks ok.

2023-08-22 13:54 UTC, noelwelsh commented
Closes #3

2023-08-23 11:14 UTC, danielost requested changes
It works great with the scatter plot, but there is an issue with lines and curves. I think that might happen because of the default `fillColor` option.

![image](https://github.com/creativescala/chartreuse/assets/72448226/0f01e619-37e1-489c-aceb-f922148bb5ef)

2023-08-23 16:42 UTC, noelwelsh commented
@danielost Good catch. I've added [this bug](creativescala/doodle#26) to fix the SVG backend. As a workaround I'll make `Line` and `Curve` override any theme fill with an empty fill.

2023-08-24 10:08 UTC, danielost approved these changes

2023-08-24 10:08 UTC, merged