Add an algorithm to calculate tick marks position
creativescala/chartreuse pull request #6
Opened 2023-06-20 18:13 UTC by danielost

### **Worked on the issue:**
- #4  

**The following PR contains the following features:**
- An algorithm that takes min and max data values as well as desired number of ticks. Output is the coordinates of the first and last ticks, and the distance between tick marks (i.e. step or tick size).
- Unit tests that cover diverse set of scenarios.

I created a separate object for axis builder methods. First I added the method directly to the `Plot` class, but we might want to access the algorithm without instantiating a `Plot` object. Also having methods like this in `Plot` would break the single responsibility principle, I suppose.

2023-06-21 13:53 UTC, noelwelsh requested changes
Overall, what is really missing is a description of what this code is intending to do. I understand the basic idea (position tick marks) but I don't understand why it makes the choices it does. Is it an issue with numeric stability? An attempt to get "good" numbers for the tick marks (and if so, what does good mean?)

2023-06-21 13:53 UTC, noelwelsh commented on core/shared/src/main/scala/chartreuse/TickMarkCalculator.scala
> +  ): (Double, Double, Double) = {
A tuple isn't a good choice to return here, as from the users point of view there are three `Double` values and there is no information to distinguish between these values. Which one is the min, which one the max, etc? The only way to know is to read the code.

Better to create a simple type

```scala
final case class Ticks(min: Double, max: Double, size: Double)
```

2023-06-21 13:53 UTC, noelwelsh commented on core/shared/src/main/scala/chartreuse/TickMarkCalculator.scala
> +    val margin: Double = (max - min) / 1e6
Why `1e6`? I think this could use some documentation.

2023-06-21 13:53 UTC, noelwelsh commented on core/shared/src/main/scala/chartreuse/TickMarkCalculator.scala
> +    val tickSizePower: Double = pow(10, -log10(roughTickSize.abs).floor)
I don't understand what this algorithm is doing. It needs some comments.

2023-06-21 13:53 UTC, noelwelsh commented on core/shared/src/main/scala/chartreuse/TickMarkCalculator.scala
> +    val tickMax: Double = ceil(max / tickSize) * tickSize
Why are we taking ceiling and floor here? Needs comments.

2023-06-22 15:03 UTC, danielost commented
Added comments for the algorithm. Writing comments like this was a new experience for me, so it took a little more time than expected. Let me know if I should add or rewrite something.
P.S. Value 1e6 is pretty arbitrary. The purpose was just to add a very little margin by dividing the range by a big number.

2023-06-26 15:49 UTC, noelwelsh reviewed
I think there are two main issues with the code as written:

1. It's not clear what invariants, if any, this algorithm maintains. For example, it can return a different number of ticks than is asked for. E.g. `calculateTickScale(0.0, 10.0, 7)` returns 6 ticks. It doesn't necessarily maintain the bounds either. E.g. `calculateTickScale(0.0, 10.0, 3)` has bounds of 0.0 and 15.0. I think only the lower bound (`min`) is maintained in the returned ticks. The algorithm doesn't have to maintain any particular invariants, but it should at least be clear on what it does and doesn't maintain.

2. I think the ticks should be centered on the bounds. E.g. `calculateTickScale(0.0, 10.0, 3)` has bounds of 0.0 and 15.0, and I think it should have bounds of -2.5 and 12.5 (or 0.0 and 10.0).

I'm thinking of how the algorithm might be changed to improve it, but I want to get you feedback sooner than I'll have time to do this.

2023-06-27 12:13 UTC, danielost commented
### Invariants:
1. The idea of returning a different number of ticks than is asked for is taken from the [flot](https://github.com/flot/flot) library. 
Its [documentation](https://github.com/flot/flot/blob/master/API.md) says: "You can specify how many ticks the algorithm aims for by setting "ticks" to a number. The algorithm always tries to generate reasonably round tick values so even if you ask for three ticks, you might get five if that fits better with the rounding."
This idea was taken as a reference.

2. The algorithm doesn't necessarily maintain any of the bounds. In the case with `calculateTickScale(0.0, 10.0, 3)` it leaves the lower bound as is because it's a multiple of the `tickSize`. The original max value (10) is not a multiple of the `tickSize`, which is 7.5. That's why we take ceiling to make it 15. For instance, `calculateTickScale(-0.5, 10.0, 3)` has bounds of -7.5 and 15 - none of the bounds are maintained in this case, as they are both not multiples of the `tickSize`. 

So, both of these behaviors are not invariants.
But we still can define some invariants for the algorithm:
1) `tickCount` should be greater than or equal to 2. This ensures that there are at least two tick marks to define a range. (Will add this check later)
2) `max` should be greater than `min`. It assumes that the range is valid and not empty. (Have to add this check as well)
3) `goodNormalizedTickSizes` list should always be sorted in ascending order. This is important for the algorithm to select the smallest value greater than or equal to the normalized tick size.
4) `tickSize` should be a positive value greater than 0, as it represents a non-empty interval between tick marks.

**Should I add these invariants to the comments?**

### Centering ticks on the bounds:
I'm not sure how to do this without significantly modifying the algorithm at the moment.
But what we really can do to decrease the gap size between input and output bounds is to add more values to `goodNormalizedTickSizes`. 
Right now it has these values:
```Scala
val goodNormalizedTickSizes: List[Double] = List(1, 1.5, 2, 2.5, 5, 7.5, 10)
```
We can experiment by adding more values. For example:
```Scala
val goodNormalizedTickSizes: List[Double] = List(1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10)
``` 

Now, `calculateTickScale(0.0, 10.0, 3)` has bounds of 0.0 and 11.0 and `tickSize` of 5.5.

2023-06-28 15:01 UTC, noelwelsh commented
1. Let's keep the algorithm as is. It's good enough for now and there is no need to block progress. If it causes problems we can return to it.
2. The method needs documentation. (That is, documentation for the method itself. Not the algorithm inside the method). This should mention the invariants that are maintained, and describe those that are not (because they are somewhat surprising).
3. Your comments are good but a bit low level. Leave them in and I might suggest alternatives if I get time, to demonstrate what I mean.
4. The naming is a bit verbose. A `TickSizeCalculator` doesn't need a method `calculateTickSize`. The name of the object clearly indicates what the method does. But this is minor and can be left.

2023-06-29 15:58 UTC, noelwelsh approved these changes
Good stuff!

2023-06-30 09:14 UTC, merged